#install basic packages
- name: install basic packages
  apt:
    name: "{{ base_pkgs }}"
    state: present
    update_cache: yes

- name: add bashtop repo
  ansible.builtin.apt_repository:
    repo: ppa:bashtop-monitor/bashtop

- name: install bashtop
  apt:
    name: bashtop
    state: present
    update_cache: yes

#Add jeydi to sudo and move the ssh key
- name: Add a new user
  user:
    name: "{{user_name}}"
    shell: /bin/bash
    password: "{{user_password}}"
- name: Add jeydi user to the sudoers
  copy:
    dest: '/etc/sudoers.d/"{{user_name}}"'
    content: '"{{user_name}}" ALL=(ALL)  NOPASSWD: ALL'
- name: Deploy SSH Key
  authorized_key: user="{{user_name}}"
                  key="{{ lookup('file', '~/.ssh/jeydit4v.pub') }}"
                  state=present

- name: Install Java Runtime Environment
  become: yes
  apt:
    name: openjdk-8-jre-headless
    state: latest
    update_cache: yes

- name: Install Java Development Kit
  become: yes
  apt:
    name: openjdk-8-jdk
    state: latest
    update_cache: yes

- name: Set JAVA_HOME variable
  copy: 
    dest: "/etc/profile.d/java.sh"
    content: "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64\n"

#TODO: what is a wheel group and why we would have a non-root user? 
# - name: Check to make sure we have a 'wheel' group
#   group:
#     name: wheel
#     state: present

# - name: Allow 'wheel' group to have passwordless sudo
#   lineinfile:
#     dest: /etc/sudoers
#     state: present
#     regexp: '^%wheel'
#     line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#     validate: 'visudo -cf %s'

# - name: Create the non-root user
#   user:
#     name: "{{ user_name }}"
#     password: "{{ user_password }}"
#     shell: "/bin/bash"
#     groups: "wheel"

#Modify ssh
- name: Add local public key for key-based SSH authentication
  authorized_key:
    user: "{{ user_name }}"
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub

- name: Change ssh port
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#Port 22'
    line: 'Port 4292'

- name: Restrict root SSH logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Force to use ssh key
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'

- name: Restrict SSH logins to keys only
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Restart sshd
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd

#Modify ufw
- name: ufw deny incoming
  ufw:
    direction: incoming
    proto: any
    policy: deny

- name: ufw allow outgoing
  ufw:
    direction: outgoing
    proto: any
    policy: allow

- name: ufw allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

- name: ufw allow port ssh
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: 4292

- name: ufw allow port ssh
  ufw:
    rule: allow
    direction: in
    proto: udp
    port: 4292

- name: enable ufw service
  ufw:
    state: enabled