FROM nginx
COPY nginx/nginx-http.conf /etc/nginx/conf.d/default.conf.template

CMD envsubst '${DOMAIN}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && \
    nginx -g 'daemon off;'