cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip

stages:
  - test
  - deploy
  - docs

image:api:
  stage: package
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: api
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_NAME -f Dockerfile_api .
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_NAME

pages:
  #Deploy gitlab pages with documentation
  image: python:3.8-buster
  # before_script:
  #   - pip install -r reqtest.txt
  stage: docs
  script:
    - pip install -r reqtest.txt
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  only:
    - develop
  except:
    - master
