FROM nginx

# Install cron
RUN apt-get update && apt-get -y install cron

# Setup the cron job to reload certificates
RUN echo "0 0 * * * root /usr/local/openresty/nginx/sbin/nginx -s reload" >> /etc/cron.d/letsencrypt

COPY nginx/nginx-https.conf /etc/nginx/conf.d/default.conf.template

CMD envsubst '${DOMAIN}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && \
    cron && \
    nginx -g 'daemon off;'
