---
- hosts: pbg_base
  vars:
    test_var: "prova"
  vars_prompt:
    - name: "user_name"
      prompt: "Enter a name for the new user"
      private: false
      confirm: false
    - name: "user_password"
      prompt: "Enter a password for the new user"
      private: true
      encrypt: "sha512_crypt"
      confirm: true
      salt_size: 7
    - name: "credential_file"
      prompt: "Enter the credential file name for the user"
      private: false
      confirm: false
  tasks:
    #Add new sudo user
    - name: Add a new user
      user:
        name: "{{user_name}}"
        shell: /bin/bash
        password: "{{user_password}}"
    - name: Copy public key to host
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: '{{ lookup("file", "../keys/" + "{{credential_file}}")}}'
      become: true
