# Create a new sudo admin
---
- hosts: [pbg, pbg_admin, bluepipe, bluepipe_admin]
  vars_prompt:
    - name: "user_name"
      prompt: "Enter a name for the new user"
      private: False
      confirm: False
    # - name: "user_password"
    #   prompt: "Enter a password for the new user"
    #   private: True
    #   encrypt: "sha512_crypt"
    #   confirm: True
    #   salt_size: 7
    - name: "credential_file"
      prompt: "Enter the credential file name for the user"
      private: False
      confirm: False
    - name: "shell_type"
      prompt: "Enter type of the shell, for example: bash"
      private: False
      confirm: False
  tasks:
    #Add new sudo user
    - name: Add a new user
      user:
        name: "{{user_name}}"
        shell: "/bin/{{shell_type}}"
        password: "$1$arBaD1Z.$szb1n0mOUSwboT.N8Y6kT0"
        update_password: always
        groups: [users, dev, docker, sudo]
      become: True

    - name: Add new user to the sudoers
      copy:
        dest: '/etc/sudoers.d/"{{user_name}}"'
        content: '"{{user_name}}" ALL=(ALL) NOPASSWD: ALL'
      become: True

    - name: Deploy SSH Key
      authorized_key: user="{{user_name}}"
        key="{{ lookup('file', './keys/authorized/' + credential_file )}}"
        state=present
      become: True

    - name: Force user to change password
      command: chage -d 0 {{user_name}}
      become: True
      # shell: "sudo chage --maxdays 30 --warndays 10 --lastday 0 {{user_name}}"
      # when: "{{ user_name }}.changed"
