# Install advance python tools: pyenv and poetry
---
- hosts: [pbg, pbg_admin, bluepipe, bluepipe_admin]
  vars_prompt:
    - name: "user_name"
      prompt: "Enter the name for the user on the machine you want to use to install pyenv and poetry"
      private: False
      confirm: False
  #   - name: "user_password"
  #     prompt: "Enter a password for the new user"
  #     private: yes
  #     encrypt: "sha512_crypt"
  #     confirm: yes
  #     salt_size: 7
  remote_user: "{{ user_name }}"
  become: True

  vars:
    poetry_version: "1.1.13"

  roles:
    - { role: roles/python_advance, tags: ["python_advance"] }
