- name: add gpg key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes
- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
  become: yes
- name: install docker
  apt:
    name: docker-ce
    state: present
  become: yes
- name: copy /etc/docker/daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  become: yes
- name: start service docker on ubuntu
  systemd:
    name: docker
    state: started
  become: yes
- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0777
    owner: root
    group: root
  become: yes
- name: create group user
  ansible.builtin.group:
    name: docker
    state: present
  become: yes
- name: add user to docker group
  user:
    name: "{{ whoami.stdout }}"
    groups: [docker]
    append: yes
  become: no
