---
################################################################
# creation of groups with ssh
- group:
    name: docker
    state: present

- group:
    name: dev
    state: present
    
- group:
    name: shiny
    state: present

################################################################
## super
- name: Create super user
  user:
    name: super
    comment: "Andrea Melloncelli"
    shell: /bin/bash
    # pwgen -1 8 10 | xargs -I '{}' sh -c 'echo -n {} "  "; openssl passwd -1 {}'
    password: "$1$Xk/PXRyn$hsqaEpRUkcHfZj7epw7nM/"
    update_password: "always" # default: "always", or "on_create"
    groups: [users, dev, sudo, docker]
  register: super
# - name: Force super to change password
#   shell: "sudo chage --maxdays 30 --warndays 10 --lastday 0 super"
#   when: super.changed
  
- name: Set authorized key for super
  authorized_key:
    user: super
    state: present
    key: '{{ item }}'
    #key_options: 'no-port-forwarding,from="10.0.1.1"'
    comment: super.super@gmail.com
  with_file: 
    - "{{ role_path }}/files/melloncelli/.ssh/id_rsa_mdpi.pub"
  run_once: yes

- name: Set sudo NOPASSWORD for super
  ansible.builtin.copy:
    src:  "{{ role_path }}/files/sudo/super"
    dest: /etc/sudoers.d/super
    validate: /usr/sbin/visudo -csf %s
    remote_src: no
    backup: no
    owner: root
    group: root
    mode: '0440'
  
################################################################
## melloncelli
- name: Create melloncelli user
  user:
    name: melloncelli
    comment: "Andrea Melloncelli"
    shell: /bin/bash
    password: "$1$R42Br4Ud$4Mdh7qI29BThA11kc2Fvy."
    update_password: "always"
    groups: [users, dev]
  register: melloncelli
# - name: Force melloncelli to change password
#   shell: "sudo chage --maxdays 30 --warndays 10 --lastday 0 melloncelli"
#   when: melloncelli.changed
  
- name: Set authorized key for melloncelli
  authorized_key:
    user: melloncelli
    state: absent
    key: '{{ item }}'
  with_file: 
    - "{{ role_path }}/files/melloncelli/.ssh/id_rsa_mdpi.pub"
  # run_once: yes

################################################################
## perlato
- name: Create perlato user
  user:
    name: perlato
    comment: "Andrea Perlato"
    shell: /bin/bash
    password: "$1$M1.1eCwf$7bKIDGdb7Qzxbov2PeHyn/"
    update_password: "always"
    groups: [users, dev]
  register: perlato
# - name: Force perlato to change password
#   shell: "sudo chage --maxdays 30 --warndays 10 --lastday 0 perlato"
#   when: perlato.changed
  
# - name: Set authorized key for perlato
#   authorized_key:
#     user: perlato
#     state: absent
#     key: '{{ item }}'
#   with_file: 
#     - "{{ role_path }}/files/claudiof/launch-ec2.pub"
#   # run_once: yes

################################################################
## pasquini
- name: Create pasquini user
  user:
    name: pasquini
    comment: "Andrea Pasquini"
    shell: /bin/bash
    password: "$1$3NhQuyr1$O5AQMm7fMiwKsvhpyaV1w."
    update_password: "always"
    groups: [users, dev]
  register: pasquini
# - name: Force pasquini to change password
#   shell: "sudo chage --maxdays 30 --warndays 10 --lastday 0 pasquini"
#   when: pasquini.changed
  
# - name: Set authorized key for pasquini
#   authorized_key:
#     user: pasquini
#     state: absent
#     key: '{{ item }}'
#   with_file: 
#     - "{{ role_path }}/files/claudiof/launch-ec2.pub"
#   # run_once: yes

# ################################################################
# ## inactive_user
# - name: Create inactive_user user
#   user:
#     name: inactive_user
#     comment: "Andrea Inactive_User"
#     shell: /bin/false
#     password: "!*"
#     update_password: "on_create"
#     groups: [users, dev]
#   register: inactive_user
# - name: Force inactive_user to change password
#   shell: "sudo chage --maxdays 30 --warndays 10 --lastday 0 inactive_user"
#   when: inactive_user.changed
  
# - name: Set authorized key for inactive_user
#   authorized_key:
#     user: inactive_user
#     state: absent
#     key: '{{ item }}'
#   with_file: 
#     - "{{ role_path }}/files/claudiof/launch-ec2.pub"
#   # run_once: yes


# ################################################################
# ## ospite ospite
# - name: Create ospite user
#   user:
#     name: ospite
#     comment: "ospite corso"
#     shell: /bin/bash
#     password: "!"
#     update_password: "on_create"
#     groups: []
#   register: ospite
# - name: Force ospite to change password
#   shell: "sudo chage --maxdays 30 --warndays 10 --lastday 0 ospite"
#   when: ospite.changed
# - name: Set expiry date for user filppo
#   shell: "sudo chage -E $(date -d +3days +%Y-%m-%d) filppo"
#   when: ospite.changed
  
# - name: Set authorized key for ospite
#   authorized_key:
#     user: ospite
#     state: present
#     key: '{{ item }}'
#   with_file: 
#     - "{{ role_path }}/files/claudiof/launch-ec2.pub"
#   run_once: yes

################################################################
## shiny
- name: Create shiny user
  user:
    name: shiny
    comment: "Shiny system user"
    shell: /bin/bash
    password: "!*"
    update_password: "always"
    groups: []
  register: shiny
# - name: Force shiny to change password
#   shell: "sudo chage --maxdays 30 --warndays 10 --lastday 0 shiny"
#   when: shiny.changed
  
# - name: Set authorized key for shiny
#   authorized_key:
#     user: shiny
#     state: present
#     key: '{{ item }}'
#   with_file: 
#     - "{{ role_path }}/files/claudiof/launch-ec2.pub"
#   run_once: yes
