- name: remove apt source file previously created by puppet
  # this can be removed in the future
  file:
    path: /etc/apt/sources.list.d/nodesource.list
    state: absent
- name: install nodejs apt key
  apt_key:
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
- name: add nodejs apt repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ node_version | default('12')}}.x {{ ansible_distribution_release }} main
    filename: nodejs
- name: install nodejs
  apt:
    name: nodejs
    state: latest
