---
# Install python
- name: Install Python base
  ansible.builtin.shell: apt -y update && apt install -y python3.8 && apt install -y python3-pip    
  become: yes


# Install pyenv
- name: install pyenv requirements
  ansible.builtin.package:
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
    state: present
  become: yes

- name: install pyenv
  ansible.builtin.shell: curl https://pyenv.run | bash

- name: add pyenv to profile
  ansible.builtin.shell: |
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile    

- name: Source bash profile.
  shell: source $HOME/.profile $HOME/.bash_profile

# - name: install python version with pyenv
#   ansible.builtin.shell: pyenv install -v 3.8.10  
#   remote_user: "{{user_name}}"

# - name: set python version to global
#   ansible.builtin.shell: pyenv global 3.8.10
#   remote_user: "{{user_name}}"

# Install poetry

