{
  "plots": { "plot1": "barplot", "plot2": "histogram", "plot3": "dynamic" },
  "dataset":
    {
      "listings": "listings_sample.csv",
      "reviews": "reviews_sample.csv",
      "calendar": "calendar_sample.csv",
    },
  "etl":
    {
      "listings": "http://data.insideairbnb.com/italy/lazio/rome/2021-02-10/data/listings.csv.gz",
      "reviews": "http://data.insideairbnb.com/italy/lazio/rome/2021-02-10/data/reviews.csv.gz",
      "calendar": "http://data.insideairbnb.com/italy/lazio/rome/2021-02-10/data/calendar.csv.gz",
    },
  "etl_results":
    {
      "listings": "listings.csv",
      "reviews": "reviews.csv",
      "calendar": "calendar.csv",
    },
  "data_path": "data",
  "csv_args":
    {
      "engine": "python",
      "sep": ",",
      "encoding": "utf-8",
      "error_bad_lines": "False",
      "nrows": 10000,
    },
}
