---
- hosts: personal_setup
  remote_user: root
  vars:
    test_var: "prova"
  vars_prompt:
    - name: "user_name"
      prompt: "Enter a name for the new user"
      private: no
      confirm: no
    - name: "user_password"
      prompt: "Enter a password for the new user"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'fail2ban', tags: 'fail2ban'}
    - {role: 'journal_dir', tags: 'journal_dir'}
    - {role: 'python', tags: 'python'}
    - {role: 'cran_r', tags: 'cran_r'}
    - {role: 'nodejs', tags: 'nodejs'}
    - {role: 'docker', tags: 'docker'}
    
