---
# Install python
- name: Install Python base 3
  ansible.builtin.shell: apt -y update && apt install -y python3 && apt install -y python3-pip
  become: True

# Install pyenv
- name: install pyenv requirements
  ansible.builtin.package:
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      # - python-openssl
      # - python-is-python3
    state: present
  become: True
